#!/bin/bash

echo "📋 SAMENVATTING: Azure OIDC Setup Script Wijzigingen"
echo "====================================================="

echo ""
echo "🔄 PARAMETER VOLGORDE WIJZIGINGEN:"
echo "=================================="
echo ""
echo "🔴 OUDE volgorde:"
echo "   1. app-name"
echo "   2. github-org"
echo "   3. github-repo"
echo "   4. branch"
echo "   5. subscription-id"
echo "   6. [verbose|management-group]"
echo "   7. [management-group-name]"
echo ""
echo "🟢 NIEUWE volgorde:"
echo "   1. subscription-id (🆕 EERSTE parameter)"
echo "   2. app-name"
echo "   3. github-org"
echo "   4. github-repo"
echo "   5. branch"
echo "   6. [verbose|management-group]"
echo "   7. [management-group-name]"
echo ""

echo "🤖 SUBSCRIPTION LOGICA:"
echo "======================="
echo ""
echo "✅ SCENARIO 1: Subscription ID meegegeven"
echo "   → Script gebruikt de opgegeven subscription"
echo "   → Valideert of subscription toegankelijk is"
echo "   → Switcht automatisch naar deze subscription"
echo ""
echo "✅ SCENARIO 2: Geen subscription ID + 1 subscription gevonden"
echo "   → Script gebruikt automatisch de enige beschikbare subscription"
echo "   → Geen gebruikersinteractie nodig"
echo ""
echo "✅ SCENARIO 3: Geen subscription ID + meerdere subscriptions gevonden"
echo "   → Script toont lijst met alle beschikbare subscriptions"
echo "   → Voor elke subscription wordt complete curl command getoond"
echo "   → Gebruiker kan copy/paste gebruiken om opnieuw te draaien"
echo "   → Script stopt met exit code 0 (geen fout)"
echo ""

echo "📝 USAGE VOORBEELDEN:"
echo "==================="
echo ""
echo "1️⃣  Basis gebruik (eenvoudigst):"
echo "   curl -s https://raw.githubusercontent.com/CXNSMB/onboarding/main/setup-app-registration.sh | bash -s -- \"SUBSCRIPTION-ID\""
echo ""
echo "2️⃣  Met custom app naam:"
echo "   curl -s https://raw.githubusercontent.com/CXNSMB/onboarding/main/setup-app-registration.sh | bash -s -- \"SUBSCRIPTION-ID\" \"my-app\""
echo ""
echo "3️⃣  Volledige configuratie:"
echo "   curl -s https://raw.githubusercontent.com/CXNSMB/onboarding/main/setup-app-registration.sh | bash -s -- \"SUBSCRIPTION-ID\" \"my-app\" \"my-org\" \"my-repo\" \"main\""
echo ""
echo "4️⃣  Met verbose mode:"
echo "   curl -s https://raw.githubusercontent.com/CXNSMB/onboarding/main/setup-app-registration.sh | bash -s -- \"SUBSCRIPTION-ID\" \"my-app\" \"my-org\" \"my-repo\" \"main\" \"verbose\""
echo ""
echo "5️⃣  Met management group:"
echo "   curl -s https://raw.githubusercontent.com/CXNSMB/onboarding/main/setup-app-registration.sh | bash -s -- \"SUBSCRIPTION-ID\" \"my-app\" \"my-org\" \"my-repo\" \"main\" \"management-group\" \"my-mg\""
echo ""
echo "6️⃣  Automatische detectie (geen subscription ID):"
echo "   curl -s https://raw.githubusercontent.com/CXNSMB/onboarding/main/setup-app-registration.sh | bash -s --"
echo ""

echo "💡 VOORDELEN:"
echo "============"
echo ""
echo "✅ Subscription ID is nu de EERSTE en meest belangrijke parameter"
echo "✅ Eenvoudiger syntax: alleen subscription ID is vaak genoeg"
echo "✅ Intelligente auto-detectie bij 1 subscription"
echo "✅ Gebruiksvriendelijke lijst bij meerdere subscriptions"
echo "✅ Copy/paste ready curl commands"
echo "✅ Geen interactieve input meer nodig"
echo "✅ Perfect voor automation en CI/CD"
echo "✅ Backward compatible (nog steeds mogelijk om alle parameters mee te geven)"
echo ""

echo "🔍 HOE SUBSCRIPTION ID TE VINDEN:"
echo "================================="
echo ""
echo "📋 Lijst alle subscriptions:"
echo "   az account list --query \"[].{name:name, id:id}\" --output table"
echo ""
echo "📋 Huidige subscription:"
echo "   az account show --query \"id\" --output tsv"
echo ""
echo "📋 Subscription van specifieke resource group:"
echo "   az group show --name \"my-rg\" --query \"id\" --output tsv | cut -d'/' -f3"
echo ""

echo "🎯 REAL WORLD EXAMPLE:"
echo "====================="
echo ""
current_sub=$(az account show --query "id" -o tsv 2>/dev/null || echo "SUBSCRIPTION-ID")
echo "Voor jouw huidige subscription:"
echo "   curl -s https://raw.githubusercontent.com/CXNSMB/onboarding/main/setup-app-registration.sh | bash -s -- \"$current_sub\" \"my-github-app\" \"my-org\" \"my-repo\" \"main\""
echo ""

echo "✅ Script is nu klaar voor productie gebruik!"
